version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  allow:
  - dependency-type: all
  ignore:
    - dependency-name: rails
      update-types:
        - version-update:semver-major
        - version-update:semver-minor

# Check for updates to GitHub Actions every week
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
