header_logo_path: ~
display_app_name_in_header: true
stage_color: <%= ENV.fetch("STAGE_COLOR", nil) %>

price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'
    cancer_center: 'Cancer Center Rate'

time_zone: "Central Time (US & Canada)"

accounts:
  # Most frequently used account by NU
  product_default: 75340
  revenue_account_default: 50617

financial:
  # in the format MM-DD
  fiscal_year_begins: 09-01
  journal_format:
    # Note that xml and xls have custom responders so they don't need a class_name
    - key: xml
    - key: xls
    - key: csv
      class_name: Journals::DefaultJournalCsv
      # mime_type: csv # This is optional if it matches the key
  default_journal_cutoff_time: "16:45"

converters:
  product_to_journal_rows: Converters::ProductToJournalRowAttributes
  order_detail_to_journal_rows: Converters::OrderDetailToJournalRowAttributes

statement_pdf:
  class_name: ExampleStatementPdf
  font_name: Roboto

validator:
  class_name: "AccountValidator::ValidatorDefault"
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: 'noreply@example.com'
  fake:
    enabled: false
    to:
    allow_list:
  exceptions:
    sender: 'noreply@example.com'
    recipients: [ 'warn@example.com', 'error@example.com' ]

support_email: ~

order_details:
  list_transformer: SplitAccounts::OrderDetailListTransformer

order_import_template_name: bulk_import_template.csv

reservations:
  grace_period: <%= 5.minutes %>
  timeout_period: <%= 12.hours %>

occupancies:
  timeout_period: <%= 12.hours %>

billing:
  review_period: <%= 7.days %>

relays:
  test:
    admin_enabled: false
    reservation_enabled: false
  development:
    admin_enabled: false
    reservation_enabled: false
  staging:
    admin_enabled: true
    reservation_enabled: false
  production:
    admin_enabled: true
    reservation_enabled: true

#
# For these settings use SettingsHelper#feature_on?
feature:
  global_billing_administrator: true
  global_billing_administrator_users_tab: true
  create_users: true
  lookup_netids: true
  limit_short_description: true
  order_assignment_notifications: true
  password_update: true
  expense_accounts: true
  edit_accounts: true
  suspend_accounts: true
  product_specific_contacts: true
  training_requests: true
  daily_view: true
  split_accounts: true
  print_order_detail: false
  user_based_price_groups: true
  my_files: true
  # results file notifications requires that my_files be on as well
  results_file_notifications: true
  set_statement_search_start_date: false
  send_statement_emails: true
  ready_for_journal_notice: true
  journals_may_span_fiscal_years: false
  equipment_list: true
  price_change_reason_required: true
  can_manage_global_price_groups: true
  cross_facility_reports: false
  product_list_columns: false
  azlist: false
  facility_tile_list: true
  use_manage: false
  facility_banner_notice: true
  charge_full_price_on_cancellation: true
  price_policy_requires_note: true
  multi_facility_accounts: true
  facility_directors_can_manage_price_groups: true
  account_reference_field: false
  facility_payment_urls: false
  uses_ldap_authentication: false
  kiosk_view: true
  bypass_kiosk_auth: false
  revenue_account_editable: false
  active_storage: true

split_accounts:
  # Roles are allowed to create Split Accounts
  create_roles:
    - administrator
    # - account_manager

# To use S3 or another Paperclip backend, you can override the configuration in the
# appropriate environment, e.g. config/settings/production.yml.
# If you wish to use it for development, add it to a `config/settings/development.local.yml`
# file (this file is gitignored).
paperclip:
  storage: filesystem
  url: ":rails_relative_url_root/system/:class/:attachment/:id_partition/:style/:safe_filename"
  path: ":rails_root/public/system/:class/:attachment/:id_partition/:style/:safe_filename"

# saml:
#   create_user: true
#   # Use login_enabled: false if you want to allow access to metadata without yet
#   # allowing login.
#   login_enabled: true
#   # You can add allowance for clock drift between the sp and idp - this is a time in seconds.
#   allowed_clock_drift_in_seconds: 0
#   idp_metadata: "https://websso.example.com/idp/metadata"
#   # certificate_file: path/to/file.p12 # Optional. Do not check in to version control.
#   # driver: # Optional. Useful to override inferred SAML settings if need be.
#   #   "idp_sso_target_url": "https://websso.example.com/idp/profile/SAML2/Redirect/SSO"
#   # metadata_parse_options: # Optional, but setting the sso_binding option is highly recommended. See RubySaml::IdpMetadataParser for valid options.
#   #   sso_binding: ["urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"] #  Otherwise the binding will default to the first one specified in the IdP by default, which can cause problems if the IdP metadata changes.
#   attribute_map:
#     "PersonImmutableID": "username"
#     "User.email": "email"
#     "User.FirstName": "first_name"
#     "User.LastName": "last_name"
#   # user_updating:
#   #  skip_attributes: email

price_policy_note_options: ~
order_detail_price_change_reason_options: ~

google_analytics_key: ~

devise:
  lock_strategy: :failed_attempts
