price_group:
  name:
    base: 'Base Rate'
    external: 'External Rate'
    cancer_center: 'Cancer Center Rate'

accounts:
  # Most frequently used account by NU
  product_default: 75340
  revenue_account_default: 50617

financial:
  # in the format MM-DD
  fiscal_year_begins: 09-01
  journal_format:
    xls: true
    csv: true
    xml: true
  default_journal_cutoff_time: "16:45"

converters:
  product_to_journal_rows: Converters::ProductToJournalRowAttributes
  order_detail_to_journal_rows: Converters::OrderDetailToJournalRowAttributes

statement_pdf:
  class_name: StatementPdf

validator:
  class_name: ValidatorDefault
  test:
    factory: # relative to Rails.root
    helper: 'spec/validator_helper' # relative to Rails.root

email:
  from: 'noreply@example.com'
  fake:
    enabled: false
    to:
    whitelist:
  exceptions:
    sender: 'noreply@example.com'
    recipients: [ 'warn@example.com', 'error@example.com' ]

order_details:
  # These hooks are triggered when an order detail enters into the status
  # The hooks can be configured with settings. Here are several formats you can use:
  #   new:
  #     - ApprovalNotification::NotifyPurchaser
  #     - ApprovalNotification::NotifyFacility
  #   inprocess:
  #     -
  #       class: ApprovalNotification::NotifyPurchaser
  #       setting_1: test3
  #     - ApprovalNotification::NotifyFacility
  #   completed: ApprovalNotification::NotifyPurchaser
  #   reconciled: ["ApprovalNotification::NotifyPurchaser", "ApprovalNotification::NotifyFacility"]
  status_change_hooks:
    pending_approval: StatusChangeNotifications::NotifyFacilityHook
    approved: StatusChangeNotifications::NotifyPurchaserHook
  list_transformer: SplitAccounts::OrderDetailListTransformer

reservations:
  grace_period: <%= 5.minutes %>

billing:
  review_period: <%= 7.days %>

external_services:
  survey: UrlService

relays:
  # can also be NetBooter::Telnet
  connect_module: NetBooter::Http
  test:
    admin_enabled: false
    reservation_enabled: false
  development:
    admin_enabled: false
    reservation_enabled: false
  staging:
    admin_enabled: true
    reservation_enabled: false
  production:
    admin_enabled: true
    reservation_enabled: true

# You should change this if you want to be able to access the API
api:
  basic_auth_name: <%= SecureRandom.hex %>
  basic_auth_password: <%= SecureRandom.hex %>

#
# For these settings use SettingsHelper#feature_on?
feature:
  billing_administrator_on: true
  create_users_on: true
  netids_on: true
  limit_short_description_on: true
  manage_payment_sources_with_users_on: true
  password_update_on: true
  recharge_accounts_on: true
  expense_accounts_on: true
  edit_accounts_on: true
  suspend_accounts_on: true
  product_specific_contacts_on: true
  training_requests_on: true
  daily_view_on: true
  split_accounts_on: true
  print_order_detail_on: false
  user_based_price_groups_on: true
  my_files_on: true
  # results file notifications requires that my_files be on as well
  results_file_notifications_on: true

# This may be overridden in settings.local.yml if your fork is using S3, so
# be sure to check there for configuration
paperclip:
  storage: filesystem
  url: ":rails_relative_url_root/:attachment/:id_partition/:style/:safe_filename"
  path: ":rails_root/public/:attachment/:id_partition/:style/:safe_filename"
