email:
  from: "nucore-noreply@nucore.stage.tablexi.com"
  fake:
    enabled: true
    to:
      - nucore@txidigital.com
    allow_list: []

# paperclip:
#   storage: s3
#   s3_credentials:
#     access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_access_key_id)) %>
#     secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_secret_access_key)) %>
#   s3_region: us-east-1
#   s3_permissions: private
#   bucket: "nucore-staging"
