email:
  from: "nucore-noreply@sandbox4500a20c96c44623a533cf4ecc2f1d05.mailgun.org"
  fake:
    enabled: true
    to:
      - nucore@wyeworks.com
    allow_list: []
    allow_domains:
      - wyeworks.com
      - txidigital.com
      - tablexi.com

# paperclip:
#   storage: s3
#   s3_credentials:
#     access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_access_key_id)) %>
#     secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", Rails.application.secrets.dig(:paperclip, :aws_secret_access_key)) %>
#   s3_region: us-east-1
#   s3_permissions: private
#   bucket: "nucore-staging"
